### ISSUE TITLE
希望添加可编辑双向绑定表格

### ISSUE THREAD

**Issue by lkmodules** [naive-ui/awesome-naive#15]
首先，native-ui是我目前见过最酷的组件库之一，已star & fork。之前使用elment-ui/el-table，可以使用slot-scope，虽然性能很差。后面使用 p-table -> umy-ui/ux-grid，这个库还没开源，目前只适配了vue2.x，elment-ui/el-table的升级版，jsx语法。可参考文档：https://www.umyui.com/umycomponent/basicEditTable。虽打算在你们组件库开发，但是考虑刚入手native-ui，有点担忧。如果有时间的话，希望能增加该组件，毕竟编辑表格使用率还是挺高的。

**Comment by 07akioni** [comment]
其实可编辑是可以实现的，但是我觉得从 API 层面没必要提供专门的配置，这块过于动态，用户没有一个统一的想法。

实际上通过自定义渲染能力 + vue 的 setup 做一个可编辑表格不会很难。

未来我们计划在官网加个 demo

**Comment by 07akioni** [comment]
我看了看你提供那个 DEMO，感觉有点意思，我们确实有可能通过属性的能力来支持一些比较简单的编辑能力

需要进一步思考
