### ISSUE TITLE
地址错误

### ISSUE THREAD

**Issue by xinjiboy1234** [naive-ui/awesome-naive#48]
[Dolphin Admin](https://dolphin-admin.bit-ocean.studio/) - 一个基于 Vue 3 + Vite + Naive UI + TypeScript + TailwindCSS 的轻量级、精致有趣的后台管理模板  , 这个链接不是一个项目地址

**Comment by XieZongChen** [comment]
@recallwei Can you update this link? If it is not updated after a week, the record will be deleted.

**Comment by XieZongChen** [comment]
> @recallwei Can you update this link? If it is not updated after a week, the record will be deleted. 重试    错误原因

[QRCode Generator](https://qrcode.bruceworld.top) The same is true for this link.

**Comment by recallwei** [comment]
https://github.com/naive-ui/awesome-naive/pull/49
